# vim ft=yaml
# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s
language: python
env:
    global:
        - DEPENDS="cython numpy scipy matplotlib h5py nibabel cvxopt"
python:
    - 2.6
before_install:
    - source tools/travis_tools.sh
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
install:
    - echo "I am here"
# command to run tests, e.g. python setup.py test
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    # Disable figure windows for matplotlib; quote to hide : from travis yaml
    - 'echo "backend : agg" > matplotlibrc'
    - cat matplotlibrc
